language: php
services: docker
php:
- 7.0
env:
  DOCKER_COMPOSE_VERSION: 1.6.2
  APP_ENV: local
  APP_DEBUG: true
  DB_CONNECTION: pgsql
  DB_HOST: postgres
  DB_PORT: 5432
  DB_DATABASE: service_db
  DB_USERNAME: service_user
  DB_PASSWORD: P@ssw0rd
  CACHE_DRIVER: array
  QUEUE_DRIVER: sync
before_install:
  - export DOCKER_REPO="${TRAVIS_REPO_SLUG,,}"
  - export IMAGE_SLUG="$TRAVIS_BRANCH.${TRAVIS_COMMIT::8}.${TRAVIS_BUILD_ID}"
  # Upgrade docker/docker-compose versions so we can use v2 of the Dockerfile format
  - docker -v
  - sudo apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-engine
  - docker -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m`" > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - cp .env.example .env
  # Stop the postgres instance travis sets up automatically
  - sudo /etc/init.d/postgresql stop
  # set env vars in the build settings to interact with repositories
  # see https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  # Start the docker stuff
  - docker-compose -v
  - docker-compose up -d
  - sleep 4
  - docker-compose ps
install:
  # Install dev php dependencies
  - docker run -i -v $(pwd):/var/www/html $(docker images -q realpage/lumen:fpm) composer install --no-interaction --prefer-dist
script:
  # Ensure phpcs triggers a failing build
  - docker exec -it $(docker-compose ps -q fpm) vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
  # Ensure breaking PSR2 compliance fails in CI
  - docker exec -it $(docker-compose ps -q fpm) vendor/bin/phpcs --standard=PSR2 --ignore=app/Http/routes.php app
  # Seed database
  - docker exec -it $(docker-compose ps -q fpm) php artisan migrate --seed
  # Run tests
  - docker exec -it $(docker-compose ps -q fpm) vendor/bin/phpunit
  # Remove preconfigured stuff and re-run tests
  - php artisan clean:template -f
  - docker exec -it $(docker-compose ps -q fpm) vendor/bin/phpunit
after_success:
  # Revert to production-only php dependencies
  - if [[ $TRAVIS_BRANCH == 'master' || $TRAVIS_BRANCH == 'staging' || $TRAVIS_BRANCH == 'develop' ]]; then docker run -i -v $(pwd):/var/www/html $(docker images -q realpage/lumen:fpm) composer install --no-interaction --no-dev --prefer-dist ; fi
  # Deployable image tags must be in format: [service].[branch].[commit-hash].[timestamp]
  - if [[ $TRAVIS_BRANCH == 'master' || $TRAVIS_BRANCH == 'staging' || $TRAVIS_BRANCH == 'develop' ]]; then docker tag "${DOCKER_REPO}:fpm" "${DOCKER_REPO}:fpm.${IMAGE_SLUG}" && docker push "${DOCKER_REPO}:fpm.${IMAGE_SLUG}" ; fi
notifications:
  slack:
    secure: 7Da36aBfrdN/RZJQhl1tuKk0h8R9fy1uTlIPnb15XDyEi5aVmDR/O+t4P30xRSAIQEZhdRs+eZtUnd6A6AqFHwHRAZqkM7RiawHBdPxu3yBQtt82QhctgSw21G4jY4XBOYTTZ3zny/+J3aYMJpMMOQnLamMEJiXTXWW2Hx3kKOuLYdfKGumdlgTdUqi6JmC1w4GoDW2nzWFYdaHkxDBIefMXD/A7kf41mowIbyCi9MkUszn7ZOuNsqmtm1JYnmF4J5X4hgi7sgT9cMxMGdV5ugcmkoj2k8Vy8knJUbgNnaz0DmtRObnlPpaXOEJpFcsKsamSZBCnf23sT1b7N2T3TjVHReddoRuRz5mv5iYmZ/al5xsvEwN5BtEukjRPvRNZvNaSQ0OayjfgZtNyOflu5/7pBZpOoLcn+YXKMfp8Ay0MlxYD3BlTqdpwct6EtnJs2K9C8hQ+8HMYA72GwmLauQbjhI7ZrV2YXs+cE9x3rFyCF0sTE/j+XtL+Xb9cTKbRwkl/PLzOyYwWqrYkMxmIfS5IUiIqTuJBBwtblu2ob7Vqq60j1vPWfkHskEsb/kTnmgsj/cNcBpVhAIr1iuykX8krtPGSRFS3bogz57cBgn/014HGSCdUAkSGMDxzGoyO9+IeDF71Uxst+pBPuWbqCorlNIj+DwL9hsNO/pbhLYE=
